### ISSUE TITLE
Camera still saving image to gallery even when setted to dont save

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-camera#35] opened 2017-03-28 05:27 UTC
_From @dzfweb on March 27, 2017 18:55_

Apparently CameraOptions is not working correctly.
Camera still saving image to gallery even when setted to dont save. 
The width and height is not working as configured too.

My code:
```
takePhoto(args) {
        let options = { width: 300, height: 300, keepAspectRatio: false, saveToGallery: false };
        let imageView = args.object.page.getViewById('image');
        camera.takePicture(options).
        then((imageAsset ) => {
            let source = new ImageSourceModule.ImageSource();
            source.fromAsset(imageAsset).then((source) => {
                console.log(`Size: ${source.width}x${source.height}`);
            });
            this.checkout.photo = source.toBase64String('png');
            imageView.src = imageAsset;
        }).catch((err) => {
            console.log('Error -> ' + err.message);
        });
    }
```

_Copied from original issue: NativeScript/NativeScript#3883_

**Comment by tsonevn** [comment] 2017-03-28 05:27
This could be related to issue [#25](https://github.com/NativeScript/nativescript-camera/issues/25) and the fact that you should request permissions for the phone gallery.

You could try to call `nativescript-camera` plugin `requestPermissions();` method before taking a picture, which will set up the needed permissions and will allow cameraOptions to be changed.

Hope this helps.

**Comment by dzfweb** [comment] 2017-03-28 12:40
@tsonevn  i already call `requestPermissions();` on ngInit function of my component, and didn't work.

**Comment by tsonevn** [comment] 2017-03-28 14:35
Hi @dzfweb, 
I have tested this scenario also on non-NativeSciprt Angular 2 project and was able to reproduce the same issue while using [CameraTest](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest) sample app.

We will research this case and will provide the needed fix. You could keep track on the issue for further info.

**Comment by dzfweb** [comment] 2017-04-04 13:56
@tsonevn do you have other alternative, or other plugin that i can use instead of nativescript-camera? I need to solve this problem in my android app. The resize isn't working too :/

**Comment by tsonevn** [comment] 2017-04-07 07:36
Hi @dzfweb,
At this time `nativescript-camera` is the only available plugin, which provides this functionality. 
About the imageSource size, you could review the comment in the issue [here](https://github.com/NativeScript/nativescript-camera/issues/36#issuecomment-292462620).

**Comment by DimitarTachev** [comment] 2017-12-06 14:58
Hi @dzfweb,

The `saveToGallery` issue is not reproducible with the latest version of the plugin. When this option is set to `false`, the images are stored in a files folder of your app (as expected).

The resizing issues will be fixed very soon, take a look at issue #26 for further details.

**Closed as completed by DimitarTachev** 2017-12-06 14:58 UTC

**Comment by mast3rd3mon** [comment] 2018-02-06 13:23
@DimitarTachev the saveToGallery is still reproducable, i have version 3.2.1 of the camera plugin and it still saves to gallery even if the parameter is set to false, can this be reopened?

**Comment by DimitarTachev** [comment] 2018-02-06 14:10
@mast3rd3mon, please open a new issue with steps to reproduce and a sample application reproducing the issue as we are not able to reproduce it on our side

**Comment by mast3rd3mon** [comment] 2018-02-06 14:13
Well i originally had 3.0.1, i updated to 3.2.1 when i saw this issue and and still
cant stop it saving to my gallery, tested on android but not ios yet

**Comment by mast3rd3mon** [comment] 2018-02-06 14:37
@DimitarTachev in your comment on december 8th, you said `The saveToGallery issue is not reproducible with the latest version of the plugin.`, could you please clarify which version that is?

**Comment by DimitarTachev** [comment] 2018-02-06 15:01
@mast3rd3mon, we are also testing with 3.2.1 and everything is working as expected. In order to investigate your case further, we will need more specific steps to reproduce the problematic behavior - something like a sample app or steps to reproduce using the plugin demo, Android version, real device or emulator, NativeScript Core Modules version, runtimes version.. (follow the issue template).

**Comment by mast3rd3mon** [comment] 2018-02-06 15:08
@DimitarTachev i created #86

**Comment by kumaratc** [comment] 2019-03-07 14:23
"nativescript-camera": "^4.1.1"

I am using the latest version and the problem is still repeated and even when i access camera i dont want the app to ask permissions to access gallery. how can we resolve these problems i am using ios.
