### ISSUE TITLE
Custom Size not respected

### ISSUE THREAD

**Issue by LorenDorez** [NativeScript/nativescript-camera#101] opened 2018-04-12 16:12 UTC
### Which platform(s) does your issue occur on?
BOTH

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): 
```
"tns-android": {
      "version": "4.0.0"
    },
    "tns-ios": {
      "version": "4.0.1"
    }
```
- Plugin(s): ` "nativescript-camera": "^4.0.2",`

### Please, tell us how to recreate the issue in as much detail as possible. 
When i try to take a picture with smaller size the imageAsset return is still very large but the image savd to the Gallery is the correct size.

The ImageAsset return is
```
_options: {
   "width": 3584,
   "height": 2688,
   "keepAspectRatio": true
 }
```

### Is there any code involved? 
```
 global.camera.takePicture({
                            height: 768,
                            width: 1024,
                            keepAspectRatio: true,
                            saveToGallery: false
                        })
```

**Comment by LorenDorez** [comment] 2018-04-12 16:36
After some debugging i found this is a result of the Density setting (3.5 for my case) but why does the image saved to the gallery show correct size of 720x1280 but the image asset return from the camera show 3584x2688?

Also maybe pass with the image asset the filePath to the picture and where it is saved so we can just access this file rather than loading the image from the asset?

**Comment by lini** [comment] 2018-04-20 08:42
The dimensions the image asset shows can be incorrect on Android devices. That is why in the demo we convert them to device independent pixels ([toDeviceIndependentPixels()](https://docs.nativescript.org/core-concepts/utils#todeviceindependentpixels-function)). 
This way you get the actual image dimensions. For example in Android:

```javascript
import { layout } from 'tns-core-modules/utils/utils';
import * as imageSourceModule from "tns-core-modules/image-source";
// ...

let source = new imageSourceModule.ImageSource();
source.fromAsset(imageAsset).then((source) => {
    let width = source.width;
    let height = source.height;
    console.log(`Size: ${width}x${height}`); 
    // will show: Size: 4096x5461

    if (app.android) {
        // the android dimensions are in device pixels
        width = layout.toDeviceIndependentPixels(width);
        height = layout.toDeviceIndependentPixels(height);
    }
    console.log(`Size: ${width}x${height}`);
    // will show: Size: 1024x1365.25
});
```

On iOS, you should get the correct image size when you inspect the ImageAsset object. For example the Iphone X should show the following for the `_options`:

```javascript
{"width":1024,"height":768,"keepAspectRatio":true}
```

**Comment by LorenDorez** [comment] 2018-05-10 21:59
Yes but how does that help with saving the image in the correct size

**Comment by erjdriver** [comment] 2018-05-10 22:33
I'm having the same issue.

The imageAsset itself is still large.

The toDeviceIndependendentPixels() divides the dimension by scale - doesn't resize the image.

**Comment by erjdriver** [comment] 2018-05-10 22:41
This seems to be the solution - I want my bitmap to be 1280x1024 or close to it.

        let _width  = platform.isIOS ? 1280 : (1280/platform.screen.mainScreen.scale);
        let _height = platform.isIOS ? 1024 : (1024/platform.screen.mainScreen.scale);
        
        let options =
        {
            width: _width,
            height: _height, 
            keepAspectRatio: true,
            saveToGallery: true
        };

**Comment by LorenDorez** [comment] 2018-05-14 14:27
@erjdriver thanks that seems to work for me too

**Comment by radeva** [comment] 2018-05-18 07:09
It seems like the issue is solved with the example above so I'm closing it.

**Closed as completed by radeva** 2018-05-18 07:09 UTC
Labels: needs more info

**Comment by LorenDorez** [comment] 2018-06-22 16:12
This seems to only work if i save the Image Asset seperately. If i use the 'SaveToGallery' option the image in the gallery is the full size.
