### ISSUE TITLE
Plugin crash when the APP is installed on SD card

### ISSUE THREAD

**Issue by wanpeng2008** [NativeScript/nativescript-camera#117] opened 2018-07-09 09:29 UTC
I am trying to install my app on the external storage, but get an error when i attempt to take picture
````
JS: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/CE67-63A3/Android/data/org.nativescript.MarketingAssistant/files/NSIMG_20180709_17162.jpg
JS:     android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:738)
JS:     android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:970)

````
It works well if i install the app on the internal storage.

My AndroidManifest.xml is 
````
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools"
		  package="__PACKAGE__"
		  android:versionCode="10000"
		  android:versionName="1.0.0.20180623_alpha">
	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>
	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>
	<uses-permission android:name="android.permission.CALL_PHONE" />
	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-feature android:name="android.hardware.camera" />
	<uses-feature android:name="android.hardware.camera.autofocus" />
	<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/post_icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme">
		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboardHidden|orientation|screenSize"
			android:theme="@style/LaunchScreenTheme">
			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
		<service android:name="com.mapbox.services.android.telemetry.service.TelemetryService" />

	</application>
</manifest>
````
Is there anything i mistake?

**Comment by tgpetrov** [comment] 2018-07-13 08:20
Hi @wanpeng2008, can you provide a little more details about this issue?
Can you try to reproduce it with the plugin's demo application and let us know how it goes? If the issue is not present in the demo app, give us the code where you are using the image-picker plugin, so we can reproduce it. If you can reproduce it with the demo, let us know if its device or emulator that you are using for testing and their exact version.

**Comment by wanpeng2008** [comment] 2018-07-13 08:48
Hi @tgpetrov , Thanks for your response. 
I'd like to prepare a demo app to reproduce this issue later.
Once it's ready, i will let you know.

**Comment by wanpeng2008** [comment] 2018-07-20 17:10
Hi @tgpetrov 
I figure out that this issue is caused by my incorrect android configuration.
Pls see https://github.com/wanpeng2008/camera-sd-issue

I used to have a file named provider_paths.xml under the folder app/App_Resources/Android/src/main/res/xml
This file has been abandoned and i forget to remove it from the app.
I don't know why this file causes the camera plugin throwing error.

provider_paths.xml:
````
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-files-path name="videos" path="." />
    <cache-path name="temps_videos" path="."/>
</paths>
````

**Comment by tgpetrov** [comment] 2018-07-27 11:11
Hi @wanpeng2008,
As part of the plugin we are also having a `provider_paths.xml` [here](https://github.com/NativeScript/nativescript-camera/blob/master/src/platforms/android/res/xml/provider_paths.xml) and it seems that your's is taking precedence causing the above issue.
If I understand you correctly, you don't need such file and when you remove it, the issue is resoled. In this case I'm closing this issue, please write again if this is not the case.

**Closed as completed by tgpetrov** 2018-07-27 11:11 UTC
